routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('{token}', ['uses' => 'URLController@redirect', 'as' => 'redirect']);

Route::group(['middleware' => 'auth'], function () {
    Route::group(['prefix' => 'urls', 'as' => 'urls.'], function () {
        Route::post('store', ['uses' => 'URLController@store', 'as' => 'store']);
        Route::delete('{url}/delete', ['uses' => 'URLController@delete', 'as' => 'delete']);
    });
});

app/Url.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Url extends Model
{
    protected $guarded = ['id'];

    public function addVisit() {
        $this->visits += 1;
        return $this;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function urls() {
        return $this->hasMany(Url::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/URLController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUrlRequest;
use App\Url;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;

class URLController extends Controller
{

    public function __construct(){}

    public function store(StoreUrlRequest $request) {
        $store = Auth::user()->urls()->create([
            'token' => $this->generate(),
            'url' => $request->url
        ]);

        if ($store) {
            Session::flash('notification', ['type' => 'success','message' => 'Succesvol een verkorte link aangemaakt!']);
        }

        return redirect()->back();
    }

    /**
     * Let the User delete the URL
     * @param Url $url
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function delete(Url $url) {

        if (Auth::user()->id !== $url->user_id)
            return redirect()->route('home')->with('notification', ['type' => 'danger','message' => 'Geen permissie om deze URL te verwijderen!']);

        $action = $url->delete();

        if (!$action)
            return redirect()->route('home')->with('notification', ['type' => 'danger','message' => 'Er ging iets mis met het verwijderen van de URL!']);

        return redirect()->route('home')->with('notification', ['type' => 'success','message' => 'Succesvol een URL verwijderd!']);
    }

    /**
     * Let the User redirect if user visits the short URL.
     * @param string $token
     * @return \Illuminate\Http\RedirectResponse
     */
    public function redirect(string $token) {
        $url = Url::where('token', $token)->first();

        if (!$url) {
            return redirect()->route('home')->with('notification', ['type' => 'warning','message' => 'Deze URL bestaat niet!']);
        }

        $url->addVisit()->save();

        return redirect()->away($url->url);
    }


    /**
     * Generating and random token for the short URL.
     * @param int $length
     * @return string
     */

    private function generate(int $length = 10) : string {
        $characters = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $token = '';

        for ($i = 0; $i < $length; $i++) {
            $token .= $characters[rand(0, strlen($characters) - 1)];
        }

        return $token;
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Jouw verkorte links') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('urls.store') }}">
                        @csrf
                        <div class="form-group">
                            <input type="text" name="url" placeholder="Jouw endpoint" class="form-control {{ $errors->has('url') ? 'is-invalid' : '' }}">

                            @if($errors->has('url'))
                                <span class="invalid-feedback">{{ $errors->first('url') }}</span>
                            @endif
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary float-right mb-2">Maak aan</button>
                        </div>
                    </form>

                    <table class="table">
                        <thead>
                            <th>URL</th>
                            <th>Endpoint</th>
                            <th>Visits</th>
                            <th></th>
                        </thead>

                        <tbody>
                            @foreach(Auth::user()->urls as $url)
                                <tr>
                                    <td>
                                        {{ $url->token }}
                                    </td>

                                    <td>
                                        {{ $url->url }}
                                    </td>

                                    <td>
                                        {{ $url->visits }}
                                    </td>

                                    <td>
                                        <form method="POST" action="{{ route('urls.delete', ['url' => $url]) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger btn-sm">Verwijder</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
           <div class="container">
               @if(Session::has('notification'))
                   <div class="alert alert-{{Session::get('notification.type')}}" role="alert">
                       {{Session::get('notification.message')}}
                   </div>
               @endif
           </div>
            @yield('content')
        </main>
    </div>
</body>
</html>